### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by pbrisbin** [LifeWay/CloudGenesis#31]
Hi there-

This seems to be the only tool around for GitOps that is CloudFormation-focused and not coupled to Kubernetes. I'm using it in [a project](https://github.com/restyled-io/ops/) and it works well, but there are various things I've [had to fix](https://github.com/LifeWay/CloudGenesis/compare/master...restyled-io:master) or want to extend.

I'm curious if this project is still being maintained because, if it is, I would try to contribute and craft my changes to increase the chances of review and acceptance. If it's not, I would probably fork and start making much more substantial (or messy) changes without concern for eventually being accepted upstream.

Thanks!

**Comment by rmmeans** [comment]
Hi! Thanks for reaching out - please do feel free to PR. We do still actively use this project and would be very grateful for any contributions. There are a couple of us that can review it. @davidhulse

**Comment by pbrisbin** [comment]
Thank you! I'm going to create distinct Issues to remind me to get my PRs together.
