### ISSUE TITLE
Use Slack blocks payload

### ISSUE THREAD

**Issue by pbrisbin** [LifeWay/CloudGenesis#36]
[`attachments` is deprecated](https://api.slack.com/reference/messaging/payload) for the new `blocks`-style. It's pretty trivial to convert.

I also notice slack-message-building is currently duplicated in 3/4 places throughout this project, having a central function/library would make this work much easier.

**Comment by rmmeans** [comment]
👍🏻  We'll also be needing to add an alternate notification hook soon for Microsoft Teams. Teams has pretty awful, non-developer friendly rate limits on notifications coming in. Given that, I would imagine slack will remain the tool of choice and the default, while we'll have an option to use Teams instead with very limited notifications going through.

**Comment by pbrisbin** [comment]
I'd love to see the notifications more extensible (IRC and Zulip are two other targets I have or would use). Maybe conditional sns handlers that do the different things based one which configuration parameters have values?
